### ISSUE TITLE
Icon Font

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#10]
We're going to need to update the icon font. Please begin to assemble an AI sprite of all the arrows, symbols and such. Thanks!

**Comment by gehalber** [comment]
Here you go:
https://www.dropbox.com/s/mzfgjvw2ook77ta/BSH_Icons.ai?dl=0

**Comment by halfempty** [comment]
@gehalber Yes, I will work on the icons this afternoon
