### ISSUE TITLE
Accordion Arrows

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#12]
These:

![image](https://cloud.githubusercontent.com/assets/775543/6381938/85801b4a-bd0a-11e4-8989-2bbe47ef6399.png)

**Comment by gehalber** [comment]
Should be in here:
https://www.dropbox.com/s/mzfgjvw2ook77ta/BSH_Icons.ai?dl=0

**Comment by gehalber** [comment]
Updated Menu icon:
https://www.dropbox.com/s/mzfgjvw2ook77ta/BSH_Icons.ai?dl=0

**Comment by halfempty** [comment]
@gehalber I think these are (also) in. Confirm?

**Comment by gehalber** [comment]
perfect.
