### ISSUE TITLE
Menu button treatment

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#13]

**Comment by halfempty** [comment]
@gehalber As we've discussed, getting the nav to expand-out at desktop sizes is something we're going to get back to once more of the other pieces are in place.

In the meantime, do you want me to do some quick work on this element:

![image](https://cloud.githubusercontent.com/assets/775543/6433179/7580ccd2-c02d-11e4-985a-d9bdf5dba636.png)

For instance, do you want it more like how it looked in the first draft?

![image](https://cloud.githubusercontent.com/assets/775543/6433183/b75d51ac-c02d-11e4-80b6-1d04895e7e0d.png)

**Comment by gehalber** [comment]
Sure.

**Comment by halfempty** [comment]
This is updated, but still awaits the icon.
