### ISSUE TITLE
Intro block

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#14]
@gehalber Some work on the "intro" block. Please take a look...

![image](https://cloud.githubusercontent.com/assets/775543/6433449/0a829372-c035-11e4-9a1b-04d4763d84a5.png)

http://bksh.etc-nyc.com/

(The illustration can be swapped-in when it's ready)

**Comment by gehalber** [comment]
Nice!

**Comment by gehalber** [comment]
I just made the padding 30 for top and bottom of the "Welcome to Brooklyn Schoolhouse" in the inspector. And giving the illustration a top margin of 50. That's feeling pretty good.

**Comment by halfempty** [comment]
Done

**Comment by gehalber** [comment]
I think the top of the house is getting cut off...

**Comment by halfempty** [comment]
@gehalber Here's what I'm seeing? 
![image](https://cloud.githubusercontent.com/assets/775543/6602490/f86354e4-c7e9-11e4-959f-3c1fc7da96a4.png)

You?

**Comment by gehalber** [comment]
Its appearing correct now. Thanks!
