### ISSUE TITLE
Next/Prev

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#15]
Note to self-- These need to be styled:
![image](https://cloud.githubusercontent.com/assets/775543/6457756/f3f1a8d0-c13f-11e4-9113-8748ff2b5105.png)

**Comment by gehalber** [comment]
I changed the menu in the dashboard, but now the prev/next are not following the order established by the main nav. Any ideas?

**Comment by halfempty** [comment]
For prev/next, change the order of the pages under the Pages section

**Comment by gehalber** [comment]
Is it ok if I remove the test pages, or unpublish them?

**Comment by halfempty** [comment]
sure

**Comment by halfempty** [comment]
@gehalber I think the styling of these is complete. Confirm?

**Comment by gehalber** [comment]
Great.

**Comment by gehalber** [comment]
Can you remove "Emergent Curriculum" from the Next/Prev?

**Comment by gehalber** [comment]
Actually, never mind about this. Closing.
