### ISSUE TITLE
Homepage Fab buttons

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#17]
@gehalber The functionality for these is in place. Accurate style is still to come:

http://bksh.etc-nyc.com/

(BTW, why are they called "Fab"s? )

**Comment by gehalber** [comment]
Floating Action Buttons…

I’m so inundated with material design now that my wife works on that team at Google.

:)

**Comment by halfempty** [comment]
@gehalber Ah! Are these supposed to float near the bottom of the window, rather than be repeated in each section?

**Comment by gehalber** [comment]
This is great. While you’re working on it I’d like to keep these buttons above the fold at all possible. If you need things to be redesigned or tweaked, let me know.

**Comment by gehalber** [comment]
Let’s just repeat them. It’ll be nicer spatially.

**Comment by halfempty** [comment]
@gehalber I think these are complete. Confirm?

**Comment by gehalber** [comment]
Can you make the hover over all buttons drop 50% less. Its feels a little too liquidy for me, even if its a google standard.

**Comment by halfempty** [comment]
@gehalber How about now?

**Comment by gehalber** [comment]
Our shadows still feel a little too spread out. I think these tighter shadows feel better. Can we more closely simulate?

![screen shot 2015-03-13 at 12 34 45 am](https://cloud.githubusercontent.com/assets/6076488/6633082/f08db716-c918-11e4-89ac-9c506bb4c6e2.png)
![screen shot 2015-03-13 at 12 34 40 am](https://cloud.githubusercontent.com/assets/6076488/6633083/f09626bc-c918-11e4-9294-a9e6d8790fe0.png)
