### ISSUE TITLE
Contact Us page

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#18]
![image](https://cloud.githubusercontent.com/assets/775543/6536104/47b1376a-c410-11e4-8489-976d664a2d08.png)

**Comment by halfempty** [comment]
@gehalber How essential is the desaturated Google Map? Off the top of my head... I think if we use a "regular" google map, it's an easy embed. But if we want a desaturated map, we'll need to do a full custom map using the API.

**Comment by gehalber** [comment]
Not important. Let’s use the regular map. We might even drop our own map in there next week. Don’t spend much time on that one. Thanks!

**Comment by gehalber** [comment]
The link color should be updated for the two column layout.
Also can you drop the facebook icon into this and link to https://www.facebook.com/brooklynschoolhouse

**Comment by halfempty** [comment]
@gehalber Feedback on this FB link?

![image](https://cloud.githubusercontent.com/assets/775543/6633242/9d89e83c-c913-11e4-8971-e07b405d24c4.png)

**Comment by gehalber** [comment]
Facebook is great.
