### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#20]
Update Facebook button to link to: https://www.facebook.com/brooklynschoolhouse

**Comment by gehalber** [comment]
Can you unbold ETC and make it the light green color?

**Comment by halfempty** [comment]
Done

**Comment by gehalber** [comment]
The Facebook is a little low. I actually tweaked the placement of copyright information as well. Take a look at page 1 of BrooklySchoolhouse-revised-4.indd in your folder for that update.

**Comment by gehalber** [comment]
I like your hover colors for the next/prev... :)

**Comment by gehalber** [comment]
Footer is looking better, I just want to try to bottom align copyright/design credit with facebook button

**Comment by gehalber** [comment]
Please change phone number to: 718.395.5415

**Comment by halfempty** [comment]
Phone number updated.

**Comment by halfempty** [comment]
Footer margins tweaked.
