### ISSUE TITLE
Pull Quote Block

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#21]
Can you remove some bottom margin from this block. I think losing about 80px would be great.

**Comment by gehalber** [comment]
Let's also make the font-size: 26px for the quote; and 22px for the byline

**Comment by gehalber** [comment]
Scratch that:
Let's also make the font-size: 27px for the quote; and 24px for the byline

**Comment by halfempty** [comment]
@gehalber These tweaks are in.

**Comment by gehalber** [comment]
![screen shot 2015-03-13 at 1 06 30 am](https://cloud.githubusercontent.com/assets/6076488/6633351/6c53bee6-c91d-11e4-9d13-69fb6e697197.png)

I'm getting a couple of spacing issues. Ideally there would be a full line break between quotes. And the read more about button would have space around it too. Anyway you can tweak?

**Comment by gehalber** [comment]
The break between quotes happens here: "The Reggia Emilia Approach..."

**Comment by halfempty** [comment]
@gehalber okay, added some padding here:

![image](https://cloud.githubusercontent.com/assets/775543/6633390/a964e506-c915-11e4-81d4-f6c1d790961e.png)

On what page is the break issue happening?

**Comment by gehalber** [comment]
homepage
the second block... there should be two qoutes separated by a full line break

**Comment by halfempty** [comment]
Like this...?
![image](https://cloud.githubusercontent.com/assets/775543/6633419/3286ce12-c916-11e4-9d4c-dd3e1b931dde.png)

(I'd lost that padding looking for the 80px to remove)

**Comment by gehalber** [comment]
Perfect. I think we're good now.

**Comment by gehalber** [comment]
Please make byline 20px and top margin 25px

**Comment by halfempty** [comment]
byline tweaked
