### ISSUE TITLE
Full Column Text Block

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#22]
Let's make the padding-bottom: 50px

**Comment by gehalber** [comment]
On this page how can we add one more full line break between the button and "Emergent Curriculum"

http://bksh.etc-nyc.com/philosophy/

**Comment by halfempty** [comment]
@gehalber we can add bottom margin to the button:

![image](https://cloud.githubusercontent.com/assets/775543/6633531/184847e0-c918-11e4-84fb-715bdfec702a.png)

(it adds it to the second one too, tho)

**Comment by gehalber** [comment]
That's good.
