### ISSUE TITLE
Apply response

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#23]
Can you make the yellow of the auto field function be the gold color of the site?

![screen shot 2015-03-13 at 12 35 25 pm](https://cloud.githubusercontent.com/assets/6076488/6642764/ac14173c-c97d-11e4-9c81-ff3526107277.png)

**Comment by gehalber** [comment]
![screen shot 2015-03-13 at 12 35 40 pm](https://cloud.githubusercontent.com/assets/6076488/6642767/b2f92b50-c97d-11e4-9c35-2e1954b79866.png)

I've updated some styles for these responses. Please see in BrooklySchoolhouse-revised-5.indd

**Comment by halfempty** [comment]
@gehalber Is BrooklySchoolhouse-revised-5.indd in the Dropbox folder? I don't see it.

Btw, the autofill color can't be changed-- that's something internal to the browser.

**Comment by gehalber** [comment]
It is. Weird.
Here’s the link:
https://www.dropbox.com/s/q8i9056t4nc9wjn/BrooklySchoolhouse-revised-5.indd?dl=0

**Comment by halfempty** [comment]
@gehalber Thanks.

Hey, I notice that's a new gold color on the form validation. Just confirming-- is that correct? Or do you want the gold from the graphic?

**Comment by gehalber** [comment]
Gold from the graphic. Thanks!

**Comment by halfempty** [comment]
@gehalber Cool, then this one should be done, then. Pls take a look:

http://brooklynschoolhouse.nyc/apply/
