### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#26]
Can you set this up?

**Comment by halfempty** [comment]
@gehalber If you want to generate the code from your end, simply grab it and go to WP -> Settings -> Google Analytics

If you'd like me to generate the code, just let me know!

**Comment by gehalber** [comment]
not sure if I have access to the new location.
Here’s the code:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-60812148-1', 'auto');
  ga('send', 'pageview');
</script>

**Comment by halfempty** [comment]
@gehalber The logins are all the same. 

http://brooklynschoolhouse.nyc/wp-admin

I've added the Google code. We should leave this open for a few days to make sure it's working.

**Comment by halfempty** [comment]
@gehalber Is the GA working correctly?

**Comment by gehalber** [comment]
Yup!
