### ISSUE TITLE
Mobile

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#27]
I'm starting the lone issue for Mobile. :)

Hopefully this is pretty straightforward for you. Would love to wrap this one up in the near future.

In your file called:
BSH_mobile web-02.indd

**Comment by halfempty** [comment]
@gehalber I did a bunch on mobile last evening. I got the nav all working, and I styled the blocks that appear on the homepage. But it's time consuming work. So the footer remains, as do the block styles that are introduced on interior pages. I'll continue plugging away!

**Comment by gehalber** [comment]
Great. Thanks Marty!

**Comment by halfempty** [comment]
@gehalber Okay, I got through the rest of the pages with mobile. Take a look?

http://brooklynschoolhouse.nyc/
