### ISSUE TITLE
Paragraph Style

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#28]
I think we might have lost our paragraph break style for 1 and 2 column body text.

http://brooklynschoolhouse.nyc/philosophy/

The break should be 22px, or just a bit bigger than a half space. Can you adjust?

**Comment by halfempty** [comment]
@gehalber Too much?

![image](https://cloud.githubusercontent.com/assets/775543/6968764/c25e6fae-d92e-11e4-8078-8e1c95f2e309.png)
