### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by halfempty** [everythingtype/brooklynschoolhouse#3]
![image](https://cloud.githubusercontent.com/assets/775543/6319323/e95bf0ec-ba7d-11e4-81ee-71d680729431.png)

What happens to the nav at responsive sizes?

**Comment by gehalber** [comment]
It will collapse into a menu, with a drop down. Our client wanted to expose the nav in desktop.

**Comment by gehalber** [comment]
sorry, it will collapse into one menu button.

**Comment by halfempty** [comment]
Like the creativity study, at small sizes, right? I should flag this as something that's possible, but somewhat complicated to develop. CSS breakpoints work really well for visual chnages, but when we want behavioral changes we have to involve JavaScript, and that gets heavier.

**Comment by gehalber** [comment]
Right. Ok. Lets leave it as a one button nav for now and then we'll talk to client about it.

**Comment by gehalber** [comment]
So for now, can you expose the nav? And we'll worry about how this is affected on mobile with javascript a bit later?

**Comment by halfempty** [comment]
@gehalber I've put in the poor-man's nav transition. That is to say, I've exposed the nav, but you can gum it up if you really try.

**Comment by gehalber** [comment]
Great! 
Can you add to the navigation “Meet Us”?

Also, when do you think you can add in the icons?
I’d love to share with our client today, if possible.

**Comment by halfempty** [comment]
@gehalber I've added it. The Menu can be modified w/o code by going to WP Dashboard -> Appearance -> Menus

**Comment by gehalber** [comment]
Oh thanks!
