### ISSUE TITLE
Quote block: gray background

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#31]
Can you make the title the dark green color?

**Comment by halfempty** [comment]
@gehalber I'm confused! Not this element, 'cause it's green already?

![bksh](https://cloud.githubusercontent.com/assets/775543/8238797/8332bbc0-15bd-11e5-93bb-6814ae09fd60.jpg)

**Comment by gehalber** [comment]
the one with the gray background.

**Comment by halfempty** [comment]
@gehalber Ah! Got it.
