### ISSUE TITLE
Workshops Page

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#32]
Posts aren't posting. 
Check out this page: http://brooklynschoolhouse.nyc/child-development-workshops/

Is there a way to enable this with the normal headline and body text styling?

**Comment by halfempty** [comment]
@gehalber Sure, this can be enabled. But firstly-- why are we trying to use a Post in this case? 

Are we adding a blog section to the site? In which case, should we provide for categories etc?

Or is this a one-off, in which case we might just as well use a Page?

**Comment by gehalber** [comment]
Good point. We will be doing a news section. This is more a one off page I guess. 
But I wouldn’t want it to be included in the linear page order (like emergent curriculum). Is there a way to bypass that?

**Comment by halfempty** [comment]
@gehalber By linear page order do you mean via the links at the bottom? 'Cause emergent curriculum is accessible that way... Should it not be?

**Comment by gehalber** [comment]
Yeah, the links at the bottom. I think its ok if emergent curriculum is, but we wouldn’t want this other page to be in the bottom order.

**Comment by halfempty** [comment]
http://brooklynschoolhouse.nyc/child-development-workshops/

For the links bit, I've ordered this after Contact Us, and then removed the "Next" link from Contact Us. I can find a more sophisitcated  solution if we end up with more pages like this, but this seems to work for now.

Also, I notice there's a missing reference in the description for workshop 4, which Kim needs to revise before sending this out.

**Comment by gehalber** [comment]
This is great for now. Thanks!

**Comment by gehalber** [comment]
This looks really good.

For the map, let's use this guy: https://snazzymaps.com/style/132/light-gray

Can the gray be the gray we're using on the rest of the site?

One tweak: Between the subheads (eg PRESS INQUIRIES) and body text it should be one full space, or 68px from base to baseline. Can you tweak that?

**Comment by gehalber** [comment]
oops! wrong field!
