### ISSUE TITLE
Pull Quote Block

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#4]
Backgrounds: white, gray
Byline
Read More text button

PS: don't worry about the squiggly underlining

![screen shot 2015-02-22 at 11 53 38 pm](https://cloud.githubusercontent.com/assets/6076488/6322943/3075a390-baee-11e4-8560-6f61288e4861.png)

**Comment by halfempty** [comment]
Test page here:
http://bksh.etc-nyc.com/test-pages/pull-quote-block/

**Comment by gehalber** [comment]
Let’s make the pull quote line height: 1.2
Make the space between quote and byline ~60px.

In the “Read More…” button, is it possible to lower the text 1 pixel or two pixels to center in the button?

**Comment by halfempty** [comment]
@gehalber I've taken another pass over this one, comparing much more closely to the InDesign. Please take a look!

**Comment by gehalber** [comment]
Beautiful!
