### ISSUE TITLE
Accordion Text Block

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#5]
Backgrounds grey and white

![screen shot 2015-02-22 at 11 55 40 pm](https://cloud.githubusercontent.com/assets/6076488/6322954/5d8fb460-baee-11e4-8837-eb86ef2f0f63.png)

**Comment by halfempty** [comment]
Test page here:
http://bksh.etc-nyc.com/test-pages/accordion-text-block/

**Comment by gehalber** [comment]
Space between left side of box and text should be 5px.
Line height should be 1.25
Add Read more button
No space after title

**Comment by halfempty** [comment]
Okay, please take a look at this one:

http://bksh.etc-nyc.com/test-pages/accordion-text-block/

**Comment by gehalber** [comment]
This looks great. Just two things:

Can you drop the arrows in from the ai sprite?
Can you make the hover over each each program fill the background white?

Then we’re good.

**Comment by halfempty** [comment]
Okay, hover white is in. The accordian arrows will be taken care of in issue #12, so I'm going to close this one.

**Comment by gehalber** [comment]
Please make the subtltle font-size: 18px

**Comment by halfempty** [comment]
@gehalber I _think_ these are 18px. Will you confirm? (I could be misunderstanding what element you're refering to)

**Comment by gehalber** [comment]
I'm talking about the text that says: 2015–2016 School Year

![screen shot 2015-03-24 at 10 05 03 pm](https://cloud.githubusercontent.com/assets/6076488/6817053/0a889714-d272-11e4-8acf-a92beeff468c.png)

**Comment by halfempty** [comment]
@gehalber Ah, got it!
