### ISSUE TITLE
Two Column

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#6]
Backgrounds: gray and white
left or right image
left or right text
Centered Title & Subtitle

Image is left aligned

![screen shot 2015-02-22 at 11 57 56 pm](https://cloud.githubusercontent.com/assets/6076488/6322972/a51e8f7c-baee-11e4-8226-3f88b9e6a9a6.png)

**Comment by halfempty** [comment]
@gehalber A start on two column...

http://bksh.etc-nyc.com/test-pages/two-column/

The images here will need a bit more attention, namely that the height should be limited (right now it will go as tall as it needs to to stretch 100% of the column).

**Comment by gehalber** [comment]
other than the height constraints, its looking really good.

**Comment by halfempty** [comment]
@gehalber Okay, image height constraint in:

http://bksh.etc-nyc.com/test-pages/two-column/

**Comment by gehalber** [comment]
Can you make the body text for the two-column text 20px?
two-column is now called "Meet Us"

**Comment by gehalber** [comment]
Let's also change the subheads to 20px too. Thanks.

**Comment by halfempty** [comment]
@gehalber Done. (By subheads I'm assuming you mean "Kim Turnbull, Founder & Director" and not "Teachers"?)

**Comment by gehalber** [comment]
yes.

**Comment by halfempty** [comment]
@gehalber cool. so this is done, then.
