### ISSUE TITLE
Single Column Text

### ISSUE THREAD

**Issue by gehalber** [everythingtype/brooklynschoolhouse#9]
Backgrounds white or gray

![screen shot 2015-02-23 at 12 05 57 am](https://cloud.githubusercontent.com/assets/6076488/6323022/cf80c6c6-baef-11e4-96cc-413f2d7abd23.png)

**Comment by halfempty** [comment]
@gehalber I'm not satisfied with the field structure of the existing "Columns" block, especially with regard to how two-columns need to act on this site. So I'm creating new, separate "One Column" and "Two Column" blocks. 

Here's Single Column:

http://bksh.etc-nyc.com/test-pages/single-column-text/

**Comment by gehalber** [comment]
This looks great!
